// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: violations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createViolation = `-- name: CreateViolation :one
INSERT INTO violations (user_id, description)
VALUES ($1, $2)
RETURNING id, user_id, description, created_at
`

type CreateViolationParams struct {
	UserID      pgtype.Int4 `json:"user_id"`
	Description string      `json:"description"`
}

func (q *Queries) CreateViolation(ctx context.Context, arg CreateViolationParams) (Violation, error) {
	row := q.db.QueryRow(ctx, createViolation, arg.UserID, arg.Description)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listViolations = `-- name: ListViolations :many
SELECT id, user_id, description, created_at
FROM violations
ORDER BY created_at DESC
`

func (q *Queries) ListViolations(ctx context.Context) ([]Violation, error) {
	rows, err := q.db.Query(ctx, listViolations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Violation
	for rows.Next() {
		var i Violation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
